services:
  workspace:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    entrypoint: [ "sh", "-c" ]
    command: [ "tail -f /dev/null" ]

volumes:
  composer-cache:
    external: false